package com.newkdroid.app;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.Gravity;
import android.widget.*;
import android.text.*;
import androidx.core.content.FileProvider;
import java.io.File;
import java.util.*;

public class MainActivity extends Activity {
    private LinearLayout list; private EditText search; private TextView status; private final List<CatalogManager.AppEntry> allApps=new ArrayList<>(); private CatalogManager manager; private int catalogVersion=0;
    private final boolean dark=true;
    private final int primary=Color.rgb(187,134,252);

    @Override protected void onCreate(Bundle b){super.onCreate(b);setTheme(R.style.Theme_NewKDroid);applyTheme();setContentView(R.layout.activity_main);manager=new CatalogManager();list=findViewById(R.id.appList);search=findViewById(R.id.searchBox);status=findViewById(R.id.statusText);findViewById(R.id.refreshButton).setOnClickListener(v->loadCatalog(true));findViewById(R.id.settingsButton).setOnClickListener(v->showSettings());findViewById(R.id.newAppsButton).setOnClickListener(v->render(""));findViewById(R.id.appsButton).setOnClickListener(v->showCategory("Приложения"));findViewById(R.id.utilitiesButton).setOnClickListener(v->showCategory("Утилиты"));findViewById(R.id.systemButton).setOnClickListener(v->showCategory("Системные"));search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString());}public void afterTextChanged(Editable e){}});loadCatalog(false);}

    private void applyTheme(){int bg=Color.rgb(18,18,20);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);getWindow().getDecorView().setSystemUiVisibility(0);}
    private void loadCatalog(boolean manual){status.setText("Обновляем каталог…");manager.loadCatalog(new CatalogManager.Callback(){public void onSuccess(List<CatalogManager.AppEntry>a,int v){runOnUiThread(()->{allApps.clear();allApps.addAll(a);catalogVersion=v;status.setText("Каталог • "+a.size()+" приложений");render(search.getText().toString());if(manual)Toast.makeText(MainActivity.this,"Каталог обновлён",Toast.LENGTH_SHORT).show();});}public void onError(Exception e){runOnUiThread(()->status.setText("Не удалось загрузить каталог. Проверьте интернет."));}});}
    private void render(String q0){list.removeAllViews();String q=q0==null?"":q0.trim().toLowerCase(Locale.ROOT);for(CatalogManager.AppEntry a:allApps){if(!q.isEmpty()&&!(a.name+" "+a.description+" "+a.category).toLowerCase(Locale.ROOT).contains(q))continue;addCard(a);}if(list.getChildCount()==0){TextView e=label("Ничего не найдено",18,Color.LTGRAY);e.setGravity(Gravity.CENTER);list.addView(e,new LinearLayout.LayoutParams(-1,180));}}
    private void showCategory(String c){list.removeAllViews();for(CatalogManager.AppEntry a:allApps)if(c.equals(a.category))addCard(a);if(list.getChildCount()==0){TextView e=label("В этой категории пока нет приложений",16,Color.LTGRAY);e.setGravity(Gravity.CENTER);list.addView(e,new LinearLayout.LayoutParams(-1,160));}}
    private void addCard(CatalogManager.AppEntry a){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(24,20,24,20);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.rgb(36,36,40));bg.setCornerRadius(28);card.setBackground(bg);card.setElevation(3);TextView t=label(a.name,20,Color.WHITE),d=label(a.description,14,Color.rgb(205,205,210)),c=label(a.category,12,Color.rgb(190,170,230)),i=label("УСТАНОВИТЬ",13,Color.rgb(220,205,240));d.setPadding(0,7,0,7);i.setGravity(Gravity.CENTER);card.addView(t);card.addView(d);card.addView(c);GradientDrawable ib=new GradientDrawable();ib.setColor(Color.rgb(58,48,70));ib.setCornerRadius(22);i.setBackground(ib);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,48);ip.topMargin=12;card.addView(i,ip);i.setOnClickListener(v->chooseRelease(a));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,16);list.addView(card,cp);}
    private TextView label(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);return t;}
    private void chooseRelease(CatalogManager.AppEntry a){Toast.makeText(this,"Получаем версии…",Toast.LENGTH_SHORT).show();manager.loadReleases(a.repository,new CatalogManager.ReleasesCallback(){public void onSuccess(List<CatalogManager.ReleaseEntry> r){runOnUiThread(()->{if(r.isEmpty()){toast("Релизов нет");return;}String[] n=new String[r.size()];for(int i=0;i<n.length;i++)n[i]=r.get(i).toString();if(r.size()==1)startDownload(r.get(0),a.name);else new AlertDialog.Builder(MainActivity.this).setTitle("Выберите версию").setItems(n,(d,w)->startDownload(r.get(w),a.name)).setNegativeButton("Отмена",null).show();});}public void onError(Exception e){runOnUiThread(()->toast("Ошибка GitHub: "+e.getMessage()));}});}
    private void startDownload(CatalogManager.ReleaseEntry release,String appName){CatalogManager.AssetEntry asset=CatalogManager.chooseApk(release);if(asset==null){toast("В этом релизе не найден подходящий APK");return;}File file=new File(getCacheDir(),"newkdroid_"+safe(appName)+"_"+safe(release.tag)+".apk");ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(100);bar.setProgress(0);TextView text=label("Подготовка скачивания…",15,Color.WHITE);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(24,12,24,12);box.addView(text);box.addView(bar);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Скачивание "+appName).setView(box).setNegativeButton("Отмена",null).create();dialog.show();manager.downloadApk(asset.downloadUrl,file,new CatalogManager.DownloadCallback(){public void onProgress(int p){runOnUiThread(()->{bar.setProgress(p);text.setText("Скачивание… "+p+"%");});}public void onSuccess(File f){runOnUiThread(()->{dialog.dismiss();installApk(f);});}public void onError(Exception e){runOnUiThread(()->{dialog.dismiss();toast("Ошибка скачивания: "+e.getMessage());});}});}
    private String safe(String s){return s==null?"app":s.replaceAll("[^A-Za-z0-9._-]","_");}
    private void installApk(File file){if(Build.VERSION.SDK_INT>=26&&!getPackageManager().canRequestPackageInstalls()){new AlertDialog.Builder(this).setTitle("Требуется разрешение").setMessage("Разрешите New KDroid устанавливать приложения из неизвестных источников.").setPositiveButton("Открыть настройки",(d,w)->{try{startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_SECURITY_SETTINGS));}}).setNegativeButton("Отмена",null).show();return;}try{Uri uri=FileProvider.getUriForFile(this,"com.newkdroid.app.fileprovider",file);Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(uri,"application/vnd.android.package-archive");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_ACTIVITY_NEW_TASK);startActivity(i);}catch(Exception e){toast("Не удалось открыть установщик: "+e.getMessage());}}

    private void showSettings(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(12,4,12,0);TextView info=label("Каталог: "+allApps.size()+" приложений\n\nПредложения по добавлению репозиториев:\ndemoda228@gmail.com",15,Color.LTGRAY);box.addView(info);TextView theme=label("Тёмная тема включена",16,Color.rgb(220,205,240));theme.setGravity(Gravity.CENTER_VERTICAL);theme.setPadding(18,18,18,18);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.rgb(58,58,64));bg.setCornerRadius(22);theme.setBackground(bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,60);p.topMargin=18;box.addView(theme,p);new AlertDialog.Builder(this).setTitle("Настройки New KDroid").setView(box).setPositiveButton("OK",null).show();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
